spring.application.name=foodapp
server.port=8080

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:*,http://127.0.0.1:*}

spring.datasource.url=jdbc:mysql://localhost:3306/foodapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=foodapp_user
spring.datasource.password=foodapp123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=false
spring.h2.console.path=/h2-console
